# Generated by Django 4.2 on 2023-05-09 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caladero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('coord_lon', models.FloatField(null=True)),
                ('coord_lat', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Capitan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Embarcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
                ('tamano_red', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Registrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio_Desembarco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=50)),
                ('coord_lon', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('coord_lat', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('costa_id', models.PositiveSmallIntegerField(choices=[(1, 'Caribe'), (2, 'Pacifico')], default=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vulgar', models.CharField(max_length=100)),
                ('nombre_taxa', models.CharField(max_length=100)),
                ('grupo_id', models.PositiveSmallIntegerField(choices=[(1, 'Crustáceos'), (2, 'Equinodermos'), (3, 'Moluscos'), (4, 'Peces'), (5, 'Poliquetos'), (6, 'Cnidarios'), (7, 'Reptiles')])),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.familia')),
            ],
        ),
        migrations.CreateModel(
            name='Desembarco_Esfuerzo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.PositiveSmallIntegerField(blank=True)),
                ('fecha_zarpe_primer', models.DateField()),
                ('pesqueria_id', models.PositiveSmallIntegerField(choices=[(1, 'CAS'), (2, 'CAP')])),
                ('lance_dia', models.PositiveSmallIntegerField(blank=True)),
                ('pescadores', models.PositiveSmallIntegerField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('capitan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.capitan')),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.embarcacion')),
                ('registrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.registrador')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.sitio_desembarco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Control_Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoreada', models.BooleanField(default=False)),
                ('registro', models.PositiveSmallIntegerField(blank=True)),
                ('pesqueria_id', models.PositiveSmallIntegerField(choices=[(1, 'CAS'), (2, 'CAP')])),
                ('fecha_zarpe_primer', models.DateField(blank=True, null=True)),
                ('fecha_zarpe_real', models.DateField(blank=True, null=True)),
                ('fecha_arribo', models.DateField(blank=True, null=True)),
                ('fecha_arribo_real', models.DateField(blank=True, null=True)),
                ('dias_no_pesca', models.PositiveSmallIntegerField()),
                ('dias_fuera_puerto', models.PositiveSmallIntegerField()),
                ('validada', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.embarcacion')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.sitio_desembarco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Captura_Esfuerzo_Abordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monitoreo', models.PositiveSmallIntegerField(blank=True)),
                ('lance', models.PositiveSmallIntegerField(blank=True)),
                ('fecha_lance', models.DateField(blank=True, null=True)),
                ('pesqueria_id', models.PositiveSmallIntegerField(choices=[(1, 'CAS'), (2, 'CAP')])),
                ('estado_mar', models.PositiveSmallIntegerField(blank=True)),
                ('longitud_cable', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('hora_inicial', models.DateTimeField(blank=True, null=True)),
                ('hora_final', models.DateTimeField(blank=True, null=True)),
                ('descarte', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('caladero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.caladero')),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.embarcacion')),
                ('registrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.registrador')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.sitio_desembarco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
