# Generated by Django 4.2 on 2023-05-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0002_especie_imagen_alter_especie_familia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caladero',
            name='coord_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='caladero',
            name='coord_lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=8, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='caladero',
            name='nombre',
            field=models.TextField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Imagen'),
        ),
    ]
