# Generated by Django 4.2 on 2023-05-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0004_alter_embarcacion_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitan',
            name='nombre',
            field=models.TextField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='registrador',
            name='nombre',
            field=models.TextField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
    ]
