# Generated by Django 4.2 on 2023-05-12 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('industrial', '0006_alter_desembarco_esfuerzo_capitan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Desembarco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.PositiveSmallIntegerField(verbose_name='Registro')),
                ('fecha_zarpe_primer', models.DateField(verbose_name='Fecha del Primer Zarpe')),
                ('pesqueria_id', models.PositiveSmallIntegerField(choices=[(1, 'CAS'), (2, 'CAP')], verbose_name='Tipo de Pesquería')),
                ('lance_dia', models.PositiveSmallIntegerField(verbose_name='Número de Lances por día')),
                ('pescadores', models.PositiveSmallIntegerField(verbose_name='Número de Pescadores')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('bandera', models.PositiveSmallIntegerField(choices=[(1, 'NO EVALUADO'), (2, 'VALIDADO'), (3, 'MALO')], default=1, verbose_name='Bandera')),
                ('capitan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.capitan', verbose_name='Capitán')),
                ('embarcacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.embarcacion', verbose_name='Embarcación')),
                ('registrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.registrador', verbose_name='Registrador de Campo')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.sitio_desembarco', verbose_name='Sitio de Desembarco')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Desembarco_Capturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_captura', models.PositiveSmallIntegerField(choices=[('CO', 'CAPTURA OBJETIVO'), ('CI', 'CAPTURA INCIDENTAL'), ('D', 'DESCARTE')], verbose_name='Tipo de Captura')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Peso (kg)')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio kilo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.categoria')),
                ('desembarco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.desembarco')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=100, unique=True, verbose_name='Nombre')),
                ('factor_conversion', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Factor de Conversión')),
            ],
        ),
        migrations.DeleteModel(
            name='Desembarco_Esfuerzo',
        ),
        migrations.AddField(
            model_name='desembarco_capturas',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.estado'),
        ),
    ]
