# Generated by Django 4.2 on 2023-05-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0009_desembarco_zonas_pesca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desembarco',
            name='user',
        ),
        migrations.AlterField(
            model_name='desembarco',
            name='zonas_pesca',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=10, null=True, verbose_name='Zonas de Pesca'),
        ),
    ]
