# Generated by Django 4.2 on 2023-05-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industrial', '0010_remove_desembarco_user_alter_desembarco_zonas_pesca'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='capitan',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='embarcacion',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='especie',
            options={'ordering': ['nombre_vulgar']},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='registrador',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='sitio_desembarco',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='desembarco',
            name='zonas_pesca',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True, verbose_name='Zonas de pesca'),
        ),
        migrations.CreateModel(
            name='Desembarco_Costos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor ($)')),
                ('costo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.costo')),
                ('desembarco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='industrial.desembarco')),
            ],
        ),
    ]
