from django.urls import path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from .views import (DesembarcoCrear, DesembarcoActualizar, delete_captura, delete_costo)

urlpatterns = [
    path('', views.acceso, name='acceso'),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('registrar/', views.registrar_usuario, name='registrar_usuario'),
    path('menu_principal/', views.menu_principal, name='menu_principal'),    
    path('sitios/', views.listar_sitio, name='listar_sitios'),    
    path('sitios/crear/', views.crear_sitio, name='crear_sitios'),        
    path('sitios/editar/<int:id>', views.editar_sitio, name='editar_sitios'),        
    path('sitios/eliminar/<int:id>', views.eliminar_sitio, name='eliminar_sitios'),            
    path('familias/', views.listar_familia, name='listar_familias'),        
    path('familias/crear/', views.crear_familia, name='crear_familias'),        
    path('familias/editar/<int:id>', views.editar_familia, name='editar_familias'),        
    path('familias/eliminar/<int:id>', views.eliminar_familia, name='eliminar_familias'),            
    path('especies/', views.listar_especie, name='listar_especies'),        
    path('especies/crear/', views.crear_especie, name='crear_especies'),        
    path('especies/editar/<int:id>', views.editar_especie, name='editar_especies'),        
    path('especies/eliminar/<int:id>', views.eliminar_especie, name='eliminar_especies'),            
    path('categorias/', views.listar_categoria, name='listar_categorias'),        
    path('categorias/crear/', views.crear_categoria, name='crear_categorias'),        
    path('categorias/editar/<int:id>', views.editar_categoria, name='editar_categorias'),        
    path('categorias/eliminar/<int:id>', views.eliminar_categoria, name='eliminar_categorias'),            
    path('estados/', views.listar_estado, name='listar_estados'),        
    path('estados/crear/', views.crear_estado, name='crear_estados'),        
    path('estados/editar/<int:id>', views.editar_estado, name='editar_estados'),        
    path('estados/eliminar/<int:id>', views.eliminar_estado, name='eliminar_estados'),                
    path('caladeros/', views.listar_caladero, name='listar_caladeros'),        
    path('caladeros/crear/', views.crear_caladero, name='crear_caladeros'),        
    path('caladeros/editar/<int:id>', views.editar_caladero, name='editar_caladeros'),        
    path('caladeros/eliminar/<int:id>', views.eliminar_caladero, name='eliminar_caladeros'),            
    path('registradores/', views.listar_registrador, name='listar_registradores'),        
    path('registradores/crear/', views.crear_registrador, name='crear_registradores'),        
    path('registradores/editar/<int:id>', views.editar_registrador, name='editar_registradores'),        
    path('registradores/eliminar/<int:id>', views.eliminar_registrador, name='eliminar_registradores'),            
    path('embarcaciones/', views.listar_embarcacion, name='listar_embarcaciones'),            
    path('embarcaciones/crear/', views.crear_embarcacion, name='crear_embarcaciones'),        
    path('embarcaciones/editar/<int:id>', views.editar_embarcacion, name='editar_embarcaciones'),        
    path('embarcaciones/eliminar/<int:id>', views.eliminar_embarcacion, name='eliminar_embarcaciones'),  
    path('costos/', views.listar_costo, name='listar_costos'),            
    path('costos/crear/', views.crear_costo, name='crear_costos'),        
    path('costos/editar/<int:id>', views.editar_costo, name='editar_costos'),        
    path('costos/eliminar/<int:id>', views.eliminar_costo, name='eliminar_costos'),            
    path('capitanes/', views.listar_capitan, name='listar_capitanes'),                
    path('capitanes/crear/', views.crear_capitan, name='crear_capitanes'),        
    path('capitanes/editar/<int:id>', views.editar_capitan, name='editar_capitanes'),        
    path('capitanes/eliminar/<int:id>', views.eliminar_capitan, name='eliminar_capitanes'),            
    path('desembarcos/', views.listar_desembarco, name='listar_desembarcos'),                    
    path('desembarcos/crear/', DesembarcoCrear.as_view(), name='crear_desembarco'),      
    path('desembarcos/editar/<int:pk>/', DesembarcoActualizar.as_view(), name='actualizar_desembarco'),
    path('desembarcos/delete-captura/<int:pk>/', delete_captura, name='delete_captura'),
    path('desembarcos/delete-costo/<int:pk>/', delete_costo, name='delete_costo'),
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 